version: '3.9'
# http://nginx.org/en/docs/http/configuring_https_servers.html

services:
  reverseproxy:
    container_name: single-https
    image: nginx:latest
    volumes:
    - ./single-https.conf:/etc/nginx/conf.d/default.conf
    - ./index.html:/usr/share/nginx/html/index.html
    - ./nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt:ro
    - ./nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key:ro
    ports:
    - 8443:8443
    - 8081:8081
    - 443:443
    - 80:80

volumes:
  data: