version: '3.9'
 
services:
  reverseproxy:
    hostname: reverseproxy
    container_name: reverseproxy
    image: nginx:latest
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    - ./reverseproxy.conf:/etc/nginx/nginx.conf
    - ./index.html:/usr/share/nginx/html/index.html
    ports:
    - 8080:8080
    depends_on:
    - nginx1
    - nginx2
  nginx1:
    hostname: nginx1
    container_name: nginx1
    image: nginx:latest
    volumes:
    - ./index-nginx-1.html:/usr/share/nginx/html/index.html
    ports:
    - 8000:80
    networks:
      - nginx-net
  nginx2:
    hostname: nginx2
    container_name: nginx2
    image: nginx:latest
    volumes:
    - ./index-nginx-2.html:/usr/share/nginx/html/index.html
    ports:
    - 8001:80
    networks:
      - nginx-net

networks:
  nginx-net:
    external: true
