version: '3.9'
 
services:
  reverseproxy:
    container_name: reverseproxy
    image: nginx:latest
    volumes:
    - ./reverseproxy.conf:/etc/nginx/conf.d/default.conf
    - ./index.html:/usr/share/nginx/html/index.html
    ports:
    - 8080:8080
    - 8081:8081
  nginx:
    container_name: nginx1
    depends_on:
    - reverseproxy
    image: nginx:latest
    volumes:
    - ./index-nginx-1.html:/usr/share/nginx/html/index.html
    ports:
    - 8080:80
  apache:
    container_name: nginx2
    depends_on:
    - reverseproxy
    image: nginx:latest
    volumes:
    - ./index-nginx-2.html:/usr/share/nginx/html/index.html
    ports:
    - 8081:80

# generation keys cert
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt